# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://silas.engineer
title: silas.engineer
email: silas.w.hughes@gmail.com
author: Silas Hughes
description: > # "If it flies, crawls, rolls, or swims, I can help you build it.
 I am a roboticist, engineer, and sUAS pilot; and I help companies build and pilot their robots.
copyright: 'Copyright &copy; 2017 Silas Hughes. All Rights Reserved.'
credits: ''


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    icon: envelope
    url: mailto:silas.w.hughes@gmail.com?Subject=I%20found%20your%20website
  - title: github
    icon: github
    url: https://github.com/silashughes
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/silas-hughes-0ab1174a
